---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[errbot::default]
    attributes:
